
const navgeneration = document.getElementById('navgeneration')
const navgeneration2 = document.getElementById('navgeneration2')
const navtheme = document.getElementById('sedes')
const alumnas = document.getElementById('alumnas')
const alumnasGene = document.getElementById('alumnas-gene')
const totalEstLima = document.getElementById('total-estud-lima')
const generaciones = document.getElementById('generaciones')
const subtitulo = document.getElementById('subtitulo')
const alumn = document.getElementById('alum')
